// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: transforms.proto

package pbtransform

import (
	proto proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BlockNumberSquare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlockNumberSquare) Reset() {
	*x = BlockNumberSquare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transforms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockNumberSquare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockNumberSquare) ProtoMessage() {}

func (x *BlockNumberSquare) ProtoReflect() protoreflect.Message {
	mi := &file_transforms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockNumberSquare.ProtoReflect.Descriptor instead.
func (*BlockNumberSquare) Descriptor() ([]byte, []int) {
	return file_transforms_proto_rawDescGZIP(), []int{0}
}

type BlockNumberSquareOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Square uint64 `protobuf:"varint,1,opt,name=square,proto3" json:"square,omitempty"`
}

func (x *BlockNumberSquareOutput) Reset() {
	*x = BlockNumberSquareOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transforms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockNumberSquareOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockNumberSquareOutput) ProtoMessage() {}

func (x *BlockNumberSquareOutput) ProtoReflect() protoreflect.Message {
	mi := &file_transforms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockNumberSquareOutput.ProtoReflect.Descriptor instead.
func (*BlockNumberSquareOutput) Descriptor() ([]byte, []int) {
	return file_transforms_proto_rawDescGZIP(), []int{1}
}

func (x *BlockNumberSquareOutput) GetSquare() uint64 {
	if x != nil {
		return x.Square
	}
	return 0
}

var File_transforms_proto protoreflect.FileDescriptor

var file_transforms_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x18, 0x73, 0x66, 0x2e, 0x62, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x13, 0x0a, 0x11,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x71, 0x75, 0x61, 0x72,
	0x65, 0x22, 0x31, 0x0a, 0x17, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x71,
	0x75, 0x61, 0x72, 0x65, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x66, 0x61, 0x73, 0x74,
	0x2f, 0x62, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x3b, 0x70, 0x62, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transforms_proto_rawDescOnce sync.Once
	file_transforms_proto_rawDescData = file_transforms_proto_rawDesc
)

func file_transforms_proto_rawDescGZIP() []byte {
	file_transforms_proto_rawDescOnce.Do(func() {
		file_transforms_proto_rawDescData = protoimpl.X.CompressGZIP(file_transforms_proto_rawDescData)
	})
	return file_transforms_proto_rawDescData
}

var file_transforms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transforms_proto_goTypes = []interface{}{
	(*BlockNumberSquare)(nil),       // 0: sf.bstream.transforms.v1.BlockNumberSquare
	(*BlockNumberSquareOutput)(nil), // 1: sf.bstream.transforms.v1.BlockNumberSquareOutput
}
var file_transforms_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transforms_proto_init() }
func file_transforms_proto_init() {
	if File_transforms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transforms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockNumberSquare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transforms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockNumberSquareOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transforms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transforms_proto_goTypes,
		DependencyIndexes: file_transforms_proto_depIdxs,
		MessageInfos:      file_transforms_proto_msgTypes,
	}.Build()
	File_transforms_proto = out.File
	file_transforms_proto_rawDesc = nil
	file_transforms_proto_goTypes = nil
	file_transforms_proto_depIdxs = nil
}
