// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sf/bstream/v1/bstream.proto

package pbbstream

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForkStep int32

const (
	ForkStep_STEP_UNKNOWN ForkStep = 0
	// Block is new head block of the chain, that is linear with the previous block
	ForkStep_STEP_NEW ForkStep = 1
	// Block is now forked and should be undone, it's not the head block of the chain anymore
	ForkStep_STEP_UNDO ForkStep = 2
	// Block is now irreversible and can be committed to (finality is chain specific, see chain documentation for more details)
	ForkStep_STEP_IRREVERSIBLE ForkStep = 4
)

// Enum value maps for ForkStep.
var (
	ForkStep_name = map[int32]string{
		0: "STEP_UNKNOWN",
		1: "STEP_NEW",
		2: "STEP_UNDO",
		4: "STEP_IRREVERSIBLE",
	}
	ForkStep_value = map[string]int32{
		"STEP_UNKNOWN":      0,
		"STEP_NEW":          1,
		"STEP_UNDO":         2,
		"STEP_IRREVERSIBLE": 4,
	}
)

func (x ForkStep) Enum() *ForkStep {
	p := new(ForkStep)
	*p = x
	return p
}

func (x ForkStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForkStep) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_bstream_v1_bstream_proto_enumTypes[0].Descriptor()
}

func (ForkStep) Type() protoreflect.EnumType {
	return &file_sf_bstream_v1_bstream_proto_enumTypes[0]
}

func (x ForkStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForkStep.Descriptor instead.
func (ForkStep) EnumDescriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{0}
}

type Protocol int32

const (
	Protocol_UNKNOWN Protocol = 0
	Protocol_EOS     Protocol = 1
	Protocol_ETH     Protocol = 2
	Protocol_SOLANA  Protocol = 3
	Protocol_NEAR    Protocol = 4
	Protocol_COSMOS  Protocol = 5
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "UNKNOWN",
		1: "EOS",
		2: "ETH",
		3: "SOLANA",
		4: "NEAR",
		5: "COSMOS",
	}
	Protocol_value = map[string]int32{
		"UNKNOWN": 0,
		"EOS":     1,
		"ETH":     2,
		"SOLANA":  3,
		"NEAR":    4,
		"COSMOS":  5,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_bstream_v1_bstream_proto_enumTypes[1].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_sf_bstream_v1_bstream_proto_enumTypes[1]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{1}
}

// Whether we can assume the data will come ordered, unless there is a chain reorganization.
// mindreaders output ordered data, whereas relayers can output unordered data.
// The server can fail early if the assumption of the caller cannot be fulfilled.
type BlockRequest_Order int32

const (
	BlockRequest_UNSPECIFIED BlockRequest_Order = 0
	BlockRequest_ORDERED     BlockRequest_Order = 1
	BlockRequest_UNORDERED   BlockRequest_Order = 2
)

// Enum value maps for BlockRequest_Order.
var (
	BlockRequest_Order_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ORDERED",
		2: "UNORDERED",
	}
	BlockRequest_Order_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ORDERED":     1,
		"UNORDERED":   2,
	}
)

func (x BlockRequest_Order) Enum() *BlockRequest_Order {
	p := new(BlockRequest_Order)
	*p = x
	return p
}

func (x BlockRequest_Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockRequest_Order) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_bstream_v1_bstream_proto_enumTypes[2].Descriptor()
}

func (BlockRequest_Order) Type() protoreflect.EnumType {
	return &file_sf_bstream_v1_bstream_proto_enumTypes[2]
}

func (x BlockRequest_Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockRequest_Order.Descriptor instead.
func (BlockRequest_Order) EnumDescriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{0, 0}
}

type BlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of blocks we want to get in burst upon connection, on a best effort basis.
	// -1 means "LIB"
	// any other "-X" value means "start at block X"
	Burst int64 `protobuf:"varint,1,opt,name=burst,proto3" json:"burst,omitempty"`
	// Type of blocks we're after here, is it 'ethereum' data, 'eos', etc.. The server can fail early
	// if he doesn't match the data he serves (services mismatch, etc..)
	ContentType   string             `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Order         BlockRequest_Order `protobuf:"varint,3,opt,name=order,proto3,enum=sf.bstream.v1.BlockRequest_Order" json:"order,omitempty"`
	Requester     string             `protobuf:"bytes,4,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{0}
}

func (x *BlockRequest) GetBurst() int64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *BlockRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BlockRequest) GetOrder() BlockRequest_Order {
	if x != nil {
		return x.Order
	}
	return BlockRequest_UNSPECIFIED
}

func (x *BlockRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

// Cursor is used to generate a string cursor, currently being utilized in forkable
type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *BlockRef              `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	HeadBlock     *BlockRef              `protobuf:"bytes,2,opt,name=head_block,json=headBlock,proto3" json:"head_block,omitempty"`
	Lib           *BlockRef              `protobuf:"bytes,3,opt,name=lib,proto3" json:"lib,omitempty"`
	Step          ForkStep               `protobuf:"varint,4,opt,name=step,proto3,enum=sf.bstream.v1.ForkStep" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{1}
}

func (x *Cursor) GetBlock() *BlockRef {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *Cursor) GetHeadBlock() *BlockRef {
	if x != nil {
		return x.HeadBlock
	}
	return nil
}

func (x *Cursor) GetLib() *BlockRef {
	if x != nil {
		return x.Lib
	}
	return nil
}

func (x *Cursor) GetStep() ForkStep {
	if x != nil {
		return x.Step
	}
	return ForkStep_STEP_UNKNOWN
}

type BlocksAndSignalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockRequest  *BlockRequest          `protobuf:"bytes,1,opt,name=block_request,json=blockRequest,proto3" json:"block_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlocksAndSignalsRequest) Reset() {
	*x = BlocksAndSignalsRequest{}
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocksAndSignalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocksAndSignalsRequest) ProtoMessage() {}

func (x *BlocksAndSignalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocksAndSignalsRequest.ProtoReflect.Descriptor instead.
func (*BlocksAndSignalsRequest) Descriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{2}
}

func (x *BlocksAndSignalsRequest) GetBlockRequest() *BlockRequest {
	if x != nil {
		return x.BlockRequest
	}
	return nil
}

type BlocksAndSignalsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*BlocksAndSignalsResponse_Block
	//	*BlocksAndSignalsResponse_Signal
	Response      isBlocksAndSignalsResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlocksAndSignalsResponse) Reset() {
	*x = BlocksAndSignalsResponse{}
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocksAndSignalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocksAndSignalsResponse) ProtoMessage() {}

func (x *BlocksAndSignalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocksAndSignalsResponse.ProtoReflect.Descriptor instead.
func (*BlocksAndSignalsResponse) Descriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{3}
}

func (x *BlocksAndSignalsResponse) GetResponse() isBlocksAndSignalsResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *BlocksAndSignalsResponse) GetBlock() *Block {
	if x != nil {
		if x, ok := x.Response.(*BlocksAndSignalsResponse_Block); ok {
			return x.Block
		}
	}
	return nil
}

func (x *BlocksAndSignalsResponse) GetSignal() *Signal {
	if x != nil {
		if x, ok := x.Response.(*BlocksAndSignalsResponse_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

type isBlocksAndSignalsResponse_Response interface {
	isBlocksAndSignalsResponse_Response()
}

type BlocksAndSignalsResponse_Block struct {
	Block *Block `protobuf:"bytes,1,opt,name=block,proto3,oneof"`
}

type BlocksAndSignalsResponse_Signal struct {
	Signal *Signal `protobuf:"bytes,2,opt,name=signal,proto3,oneof"`
}

func (*BlocksAndSignalsResponse_Block) isBlocksAndSignalsResponse_Response() {}

func (*BlocksAndSignalsResponse_Signal) isBlocksAndSignalsResponse_Response() {}

type Signal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Signal:
	//
	//	*Signal_BlockCommitmentSignal
	Signal        isSignal_Signal `protobuf_oneof:"signal"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{4}
}

func (x *Signal) GetSignal() isSignal_Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *Signal) GetBlockCommitmentSignal() *BlockCommitmentSignal {
	if x != nil {
		if x, ok := x.Signal.(*Signal_BlockCommitmentSignal); ok {
			return x.BlockCommitmentSignal
		}
	}
	return nil
}

type isSignal_Signal interface {
	isSignal_Signal()
}

type Signal_BlockCommitmentSignal struct {
	BlockCommitmentSignal *BlockCommitmentSignal `protobuf:"bytes,1,opt,name=block_commitment_signal,json=blockCommitmentSignal,proto3,oneof"`
}

func (*Signal_BlockCommitmentSignal) isSignal_Signal() {}

type BlockCommitmentSignal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockId         string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	BlockNumber     string                 `protobuf:"bytes,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	CommitmentLevel int32                  `protobuf:"varint,3,opt,name=commitment_level,json=commitmentLevel,proto3" json:"commitment_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockCommitmentSignal) Reset() {
	*x = BlockCommitmentSignal{}
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCommitmentSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCommitmentSignal) ProtoMessage() {}

func (x *BlockCommitmentSignal) ProtoReflect() protoreflect.Message {
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCommitmentSignal.ProtoReflect.Descriptor instead.
func (*BlockCommitmentSignal) Descriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{5}
}

func (x *BlockCommitmentSignal) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockCommitmentSignal) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *BlockCommitmentSignal) GetCommitmentLevel() int32 {
	if x != nil {
		return x.CommitmentLevel
	}
	return 0
}

// Block is the chain agnostic representation of a block. It contains the block
// metadata like num, hash, parent num, etc as well as containing the payload.
//
// **Required** Any changes to non-payload field on this object must be
// reflected in `BlockMeta` as well!
type Block struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Number    uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Id        string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ParentId  string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LibNum    uint64                 `protobuf:"varint,5,opt,name=lib_num,json=libNum,proto3" json:"lib_num,omitempty"`
	// Deprecated: Marked as deprecated in sf/bstream/v1/bstream.proto.
	PayloadKind Protocol `protobuf:"varint,6,opt,name=payload_kind,json=payloadKind,proto3,enum=sf.bstream.v1.Protocol" json:"payload_kind,omitempty"`
	// Deprecated: Marked as deprecated in sf/bstream/v1/bstream.proto.
	PayloadVersion int32 `protobuf:"varint,7,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	// Deprecated: Marked as deprecated in sf/bstream/v1/bstream.proto.
	PayloadBuffer []byte `protobuf:"bytes,8,opt,name=payload_buffer,json=payloadBuffer,proto3" json:"payload_buffer,omitempty"`
	// Deprecated: Marked as deprecated in sf/bstream/v1/bstream.proto.
	HeadNum         uint64     `protobuf:"varint,9,opt,name=head_num,json=headNum,proto3" json:"head_num,omitempty"`
	ParentNum       uint64     `protobuf:"varint,10,opt,name=parent_num,json=parentNum,proto3" json:"parent_num,omitempty"`
	Payload         *anypb.Any `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	CommitmentLevel int32      `protobuf:"varint,12,opt,name=commitment_level,json=commitmentLevel,proto3" json:"commitment_level,omitempty"` //    commitment level of the block, ex: '0' for processed, '10' for confirmed, '100' for finalized, flash blocks could be from -20 to -10
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{6}
}

func (x *Block) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Block) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Block) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Block) GetLibNum() uint64 {
	if x != nil {
		return x.LibNum
	}
	return 0
}

// Deprecated: Marked as deprecated in sf/bstream/v1/bstream.proto.
func (x *Block) GetPayloadKind() Protocol {
	if x != nil {
		return x.PayloadKind
	}
	return Protocol_UNKNOWN
}

// Deprecated: Marked as deprecated in sf/bstream/v1/bstream.proto.
func (x *Block) GetPayloadVersion() int32 {
	if x != nil {
		return x.PayloadVersion
	}
	return 0
}

// Deprecated: Marked as deprecated in sf/bstream/v1/bstream.proto.
func (x *Block) GetPayloadBuffer() []byte {
	if x != nil {
		return x.PayloadBuffer
	}
	return nil
}

// Deprecated: Marked as deprecated in sf/bstream/v1/bstream.proto.
func (x *Block) GetHeadNum() uint64 {
	if x != nil {
		return x.HeadNum
	}
	return 0
}

func (x *Block) GetParentNum() uint64 {
	if x != nil {
		return x.ParentNum
	}
	return 0
}

func (x *Block) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Block) GetCommitmentLevel() int32 {
	if x != nil {
		return x.CommitmentLevel
	}
	return 0
}

// BlockMeta is strictly equivalent to Block, except that it doesn't contain the payload
// nor any field related to payload.
//
// First, it's used to store block meta information on disk or on a KV store. Second,
// it serves the purpose of being a lighter version of Block, that can to `proto.Unmarshal`
// a real `Block` while ignoring the payload.
//
// **Required** Alignment of the fields in this struct is **required** to be the same as
// `Block` to allow for `proto.Unmarshal` to work.
type BlockMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LibNum        uint64                 `protobuf:"varint,5,opt,name=lib_num,json=libNum,proto3" json:"lib_num,omitempty"`
	ParentNum     uint64                 `protobuf:"varint,10,opt,name=parent_num,json=parentNum,proto3" json:"parent_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockMeta) Reset() {
	*x = BlockMeta{}
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMeta) ProtoMessage() {}

func (x *BlockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMeta.ProtoReflect.Descriptor instead.
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{7}
}

func (x *BlockMeta) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockMeta) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *BlockMeta) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BlockMeta) GetLibNum() uint64 {
	if x != nil {
		return x.LibNum
	}
	return 0
}

func (x *BlockMeta) GetParentNum() uint64 {
	if x != nil {
		return x.ParentNum
	}
	return 0
}

type BlockRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint64                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRef) Reset() {
	*x = BlockRef{}
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRef) ProtoMessage() {}

func (x *BlockRef) ProtoReflect() protoreflect.Message {
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRef.ProtoReflect.Descriptor instead.
func (*BlockRef) Descriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{8}
}

func (x *BlockRef) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *BlockRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GenericBlockIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            []*KeyToBitmap         `protobuf:"bytes,4,rep,name=kv,proto3" json:"kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericBlockIndex) Reset() {
	*x = GenericBlockIndex{}
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericBlockIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericBlockIndex) ProtoMessage() {}

func (x *GenericBlockIndex) ProtoReflect() protoreflect.Message {
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericBlockIndex.ProtoReflect.Descriptor instead.
func (*GenericBlockIndex) Descriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{9}
}

func (x *GenericBlockIndex) GetKv() []*KeyToBitmap {
	if x != nil {
		return x.Kv
	}
	return nil
}

type KeyToBitmap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Bitmap        []byte                 `protobuf:"bytes,2,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyToBitmap) Reset() {
	*x = KeyToBitmap{}
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyToBitmap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyToBitmap) ProtoMessage() {}

func (x *KeyToBitmap) ProtoReflect() protoreflect.Message {
	mi := &file_sf_bstream_v1_bstream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyToBitmap.ProtoReflect.Descriptor instead.
func (*KeyToBitmap) Descriptor() ([]byte, []int) {
	return file_sf_bstream_v1_bstream_proto_rawDescGZIP(), []int{10}
}

func (x *KeyToBitmap) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyToBitmap) GetBitmap() []byte {
	if x != nil {
		return x.Bitmap
	}
	return nil
}

var File_sf_bstream_v1_bstream_proto protoreflect.FileDescriptor

const file_sf_bstream_v1_bstream_proto_rawDesc = "" +
	"\n" +
	"\x1bsf/bstream/v1/bstream.proto\x12\rsf.bstream.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xd4\x01\n" +
	"\fBlockRequest\x12\x14\n" +
	"\x05burst\x18\x01 \x01(\x03R\x05burst\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x127\n" +
	"\x05order\x18\x03 \x01(\x0e2!.sf.bstream.v1.BlockRequest.OrderR\x05order\x12\x1c\n" +
	"\trequester\x18\x04 \x01(\tR\trequester\"4\n" +
	"\x05Order\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aORDERED\x10\x01\x12\r\n" +
	"\tUNORDERED\x10\x02\"\xc7\x01\n" +
	"\x06Cursor\x12-\n" +
	"\x05block\x18\x01 \x01(\v2\x17.sf.bstream.v1.BlockRefR\x05block\x126\n" +
	"\n" +
	"head_block\x18\x02 \x01(\v2\x17.sf.bstream.v1.BlockRefR\theadBlock\x12)\n" +
	"\x03lib\x18\x03 \x01(\v2\x17.sf.bstream.v1.BlockRefR\x03lib\x12+\n" +
	"\x04step\x18\x04 \x01(\x0e2\x17.sf.bstream.v1.ForkStepR\x04step\"[\n" +
	"\x17BlocksAndSignalsRequest\x12@\n" +
	"\rblock_request\x18\x01 \x01(\v2\x1b.sf.bstream.v1.BlockRequestR\fblockRequest\"\x85\x01\n" +
	"\x18BlocksAndSignalsResponse\x12,\n" +
	"\x05block\x18\x01 \x01(\v2\x14.sf.bstream.v1.BlockH\x00R\x05block\x12/\n" +
	"\x06signal\x18\x02 \x01(\v2\x15.sf.bstream.v1.SignalH\x00R\x06signalB\n" +
	"\n" +
	"\bresponse\"r\n" +
	"\x06Signal\x12^\n" +
	"\x17block_commitment_signal\x18\x01 \x01(\v2$.sf.bstream.v1.BlockCommitmentSignalH\x00R\x15blockCommitmentSignalB\b\n" +
	"\x06signal\"\x80\x01\n" +
	"\x15BlockCommitmentSignal\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12!\n" +
	"\fblock_number\x18\x02 \x01(\tR\vblockNumber\x12)\n" +
	"\x10commitment_level\x18\x03 \x01(\x05R\x0fcommitmentLevel\"\xd0\x03\n" +
	"\x05Block\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\alib_num\x18\x05 \x01(\x04R\x06libNum\x12>\n" +
	"\fpayload_kind\x18\x06 \x01(\x0e2\x17.sf.bstream.v1.ProtocolB\x02\x18\x01R\vpayloadKind\x12+\n" +
	"\x0fpayload_version\x18\a \x01(\x05B\x02\x18\x01R\x0epayloadVersion\x12)\n" +
	"\x0epayload_buffer\x18\b \x01(\fB\x02\x18\x01R\rpayloadBuffer\x12\x1d\n" +
	"\bhead_num\x18\t \x01(\x04B\x02\x18\x01R\aheadNum\x12\x1d\n" +
	"\n" +
	"parent_num\x18\n" +
	" \x01(\x04R\tparentNum\x12.\n" +
	"\apayload\x18\v \x01(\v2\x14.google.protobuf.AnyR\apayload\x12)\n" +
	"\x10commitment_level\x18\f \x01(\x05R\x0fcommitmentLevel\"\xc2\x01\n" +
	"\tBlockMeta\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\alib_num\x18\x05 \x01(\x04R\x06libNum\x12\x1d\n" +
	"\n" +
	"parent_num\x18\n" +
	" \x01(\x04R\tparentNum\",\n" +
	"\bBlockRef\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x04R\x03num\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"Q\n" +
	"\x11GenericBlockIndex\x12*\n" +
	"\x02kv\x18\x04 \x03(\v2\x1a.sf.bstream.v1.KeyToBitmapR\x02kvJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04\"7\n" +
	"\vKeyToBitmap\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x16\n" +
	"\x06bitmap\x18\x02 \x01(\fR\x06bitmap*\\\n" +
	"\bForkStep\x12\x10\n" +
	"\fSTEP_UNKNOWN\x10\x00\x12\f\n" +
	"\bSTEP_NEW\x10\x01\x12\r\n" +
	"\tSTEP_UNDO\x10\x02\x12\x15\n" +
	"\x11STEP_IRREVERSIBLE\x10\x04\"\x04\b\x03\x10\x03\"\x04\b\x05\x10\x05*K\n" +
	"\bProtocol\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03EOS\x10\x01\x12\a\n" +
	"\x03ETH\x10\x02\x12\n" +
	"\n" +
	"\x06SOLANA\x10\x03\x12\b\n" +
	"\x04NEAR\x10\x04\x12\n" +
	"\n" +
	"\x06COSMOS\x10\x052\xb3\x01\n" +
	"\vBlockStream\x12=\n" +
	"\x06Blocks\x12\x1b.sf.bstream.v1.BlockRequest\x1a\x14.sf.bstream.v1.Block0\x01\x12e\n" +
	"\x10BlocksAndSignals\x12&.sf.bstream.v1.BlocksAndSignalsRequest\x1a'.sf.bstream.v1.BlocksAndSignalsResponse0\x01B=Z;github.com/streamingfast/bstream/pb/sf/bstream/v1;pbbstreamb\x06proto3"

var (
	file_sf_bstream_v1_bstream_proto_rawDescOnce sync.Once
	file_sf_bstream_v1_bstream_proto_rawDescData []byte
)

func file_sf_bstream_v1_bstream_proto_rawDescGZIP() []byte {
	file_sf_bstream_v1_bstream_proto_rawDescOnce.Do(func() {
		file_sf_bstream_v1_bstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_bstream_v1_bstream_proto_rawDesc), len(file_sf_bstream_v1_bstream_proto_rawDesc)))
	})
	return file_sf_bstream_v1_bstream_proto_rawDescData
}

var file_sf_bstream_v1_bstream_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sf_bstream_v1_bstream_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sf_bstream_v1_bstream_proto_goTypes = []any{
	(ForkStep)(0),                    // 0: sf.bstream.v1.ForkStep
	(Protocol)(0),                    // 1: sf.bstream.v1.Protocol
	(BlockRequest_Order)(0),          // 2: sf.bstream.v1.BlockRequest.Order
	(*BlockRequest)(nil),             // 3: sf.bstream.v1.BlockRequest
	(*Cursor)(nil),                   // 4: sf.bstream.v1.Cursor
	(*BlocksAndSignalsRequest)(nil),  // 5: sf.bstream.v1.BlocksAndSignalsRequest
	(*BlocksAndSignalsResponse)(nil), // 6: sf.bstream.v1.BlocksAndSignalsResponse
	(*Signal)(nil),                   // 7: sf.bstream.v1.Signal
	(*BlockCommitmentSignal)(nil),    // 8: sf.bstream.v1.BlockCommitmentSignal
	(*Block)(nil),                    // 9: sf.bstream.v1.Block
	(*BlockMeta)(nil),                // 10: sf.bstream.v1.BlockMeta
	(*BlockRef)(nil),                 // 11: sf.bstream.v1.BlockRef
	(*GenericBlockIndex)(nil),        // 12: sf.bstream.v1.GenericBlockIndex
	(*KeyToBitmap)(nil),              // 13: sf.bstream.v1.KeyToBitmap
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(*anypb.Any)(nil),                // 15: google.protobuf.Any
}
var file_sf_bstream_v1_bstream_proto_depIdxs = []int32{
	2,  // 0: sf.bstream.v1.BlockRequest.order:type_name -> sf.bstream.v1.BlockRequest.Order
	11, // 1: sf.bstream.v1.Cursor.block:type_name -> sf.bstream.v1.BlockRef
	11, // 2: sf.bstream.v1.Cursor.head_block:type_name -> sf.bstream.v1.BlockRef
	11, // 3: sf.bstream.v1.Cursor.lib:type_name -> sf.bstream.v1.BlockRef
	0,  // 4: sf.bstream.v1.Cursor.step:type_name -> sf.bstream.v1.ForkStep
	3,  // 5: sf.bstream.v1.BlocksAndSignalsRequest.block_request:type_name -> sf.bstream.v1.BlockRequest
	9,  // 6: sf.bstream.v1.BlocksAndSignalsResponse.block:type_name -> sf.bstream.v1.Block
	7,  // 7: sf.bstream.v1.BlocksAndSignalsResponse.signal:type_name -> sf.bstream.v1.Signal
	8,  // 8: sf.bstream.v1.Signal.block_commitment_signal:type_name -> sf.bstream.v1.BlockCommitmentSignal
	14, // 9: sf.bstream.v1.Block.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 10: sf.bstream.v1.Block.payload_kind:type_name -> sf.bstream.v1.Protocol
	15, // 11: sf.bstream.v1.Block.payload:type_name -> google.protobuf.Any
	14, // 12: sf.bstream.v1.BlockMeta.timestamp:type_name -> google.protobuf.Timestamp
	13, // 13: sf.bstream.v1.GenericBlockIndex.kv:type_name -> sf.bstream.v1.KeyToBitmap
	3,  // 14: sf.bstream.v1.BlockStream.Blocks:input_type -> sf.bstream.v1.BlockRequest
	5,  // 15: sf.bstream.v1.BlockStream.BlocksAndSignals:input_type -> sf.bstream.v1.BlocksAndSignalsRequest
	9,  // 16: sf.bstream.v1.BlockStream.Blocks:output_type -> sf.bstream.v1.Block
	6,  // 17: sf.bstream.v1.BlockStream.BlocksAndSignals:output_type -> sf.bstream.v1.BlocksAndSignalsResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sf_bstream_v1_bstream_proto_init() }
func file_sf_bstream_v1_bstream_proto_init() {
	if File_sf_bstream_v1_bstream_proto != nil {
		return
	}
	file_sf_bstream_v1_bstream_proto_msgTypes[3].OneofWrappers = []any{
		(*BlocksAndSignalsResponse_Block)(nil),
		(*BlocksAndSignalsResponse_Signal)(nil),
	}
	file_sf_bstream_v1_bstream_proto_msgTypes[4].OneofWrappers = []any{
		(*Signal_BlockCommitmentSignal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_bstream_v1_bstream_proto_rawDesc), len(file_sf_bstream_v1_bstream_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sf_bstream_v1_bstream_proto_goTypes,
		DependencyIndexes: file_sf_bstream_v1_bstream_proto_depIdxs,
		EnumInfos:         file_sf_bstream_v1_bstream_proto_enumTypes,
		MessageInfos:      file_sf_bstream_v1_bstream_proto_msgTypes,
	}.Build()
	File_sf_bstream_v1_bstream_proto = out.File
	file_sf_bstream_v1_bstream_proto_goTypes = nil
	file_sf_bstream_v1_bstream_proto_depIdxs = nil
}
